[package]
name = "unshrouded"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.14.0"
hex = "0.4.3"
crc = "3.2.1"
fnv_rs = "0.4.3"
